# Generated by Django 5.2.5 on 2025-08-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css3two_blog', '0002_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
